### ISSUE TITLE
Characters Scroll

### ISSUE THREAD

**Issue by TonybynMp4** [marcostom32/qb-multicharacter#8]
It'd be cool to be able to scroll through the characters when you got more than 7 and to move the register / play / delete under the character's infos to make it work with more than 5/ 6 characters (rn to have it work properly you can only have 5 maximum)

**Comment by SirOMGitsYOU** [comment]
+1 i think this would be an excellent idea

**Comment by YungT-SevsideRP** [comment]
did yall find a way to do so?
